name: Terraform Destroy EKS

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Environment to destroy"
        required: true
        type: choice
        options:
          - dev
          - production

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      TF_STATE_REGION: ${{ secrets.TF_STATE_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init (Remote Backend)
        run: |
          terraform init \
            -backend-config="bucket=my-eks-terraform-state-us-east-1" \
            -backend-config="key=eks/${CLUSTER_NAME}/terraform.tfstate"
            -backend-config="region=${AWS_REGION}" \ 
            -backend-config="dynamodb_table=terraform-locks" \
            -backend-config="encrypt=true"

      - name: Terraform Plan Destroy
        run: |
          terraform plan -destroy \
            -var="aws_region=${AWS_REGION}" \
            -var="cluster_name=${CLUSTER_NAME}"

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve -refresh=true \
            -var="aws_region=${AWS_REGION}" \
            -var="cluster_name=${CLUSTER_NAME}"

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify Cluster Deletion
        run: |
          aws eks describe-cluster --name ${CLUSTER_NAME} \
          || echo "Cluster not found â€“ deletion successful"

      - name: Delete Terraform State File
        run: |
          aws s3 rm s3://my-eks-terraform-state/eks/${CLUSTER_NAME}/terraform.tfstate
      - name: Delete S3 Bucket (if empty)
        run: |
          aws s3 rb s3://my-eks-terraform-state --force || echo "Bucket not empty or does not exist"  